### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by musawarbilal786** [jzielinski47/react-native-alarm-clock-app#1]
Can you please share all missing files ?
can you help me how to clone and run this project ?

**Comment by jzielinski47** [comment]
hey, no files are missing. To install the project follow these steps:

1. Download the project.
2. Unzip the downloaded file.
3. Open the folder with Visual Studio Code
4. Open up a terminal
5. Run `npm install` or `npm i`
6. Run `npm start` (that should run expo) 
7. You should be able to run the project with an expo app as it will show you the remaining steps

If there is any issue or a problem, please let me know. And thank you for your interest in the project.
I've seen you've got a similar project yourself, do you?

**Comment by jzielinski47** [comment]
an alternative would be opening the directory directly in a terminal not using the visual code as its redundant in this case
